#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Apr 30 16:18:46 IST 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2eb18a5bf9ec4666b114743800cde057 --debug typical --relax --mt 8 -d "NO_OF_TRANSACTIONS=2000" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot adder_4_bit_tb_top_behav xil_defaultlib.adder_4_bit_tb_top xil_defaultlib.glbl -log elaborate.log -L UVM -timescale 1ns/1ps"
xelab -wto 2eb18a5bf9ec4666b114743800cde057 --debug typical --relax --mt 8 -d "NO_OF_TRANSACTIONS=2000" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot adder_4_bit_tb_top_behav xil_defaultlib.adder_4_bit_tb_top xil_defaultlib.glbl -log elaborate.log -L UVM -timescale 1ns/1ps

